DROP DATABASE IF EXISTS company_db;

CREATE DATABASE company_db DEFAULT CHARACTER SET utf8;

USE company_db;

CREATE TABLE Users(
	Id INT UNSIGNED NOT NULL AUTO_INCREMENT,
	Login VARCHAR(20) NOT NULL UNIQUE,
	Password CHAR(64) NOT NULL UNIQUE,
	Role TINYINT UNSIGNED DEFAULT 3,
	PRIMARY KEY (Id)
) ENGINE=INNODB DEFAULT CHARACTER SET utf8;

CREATE TABLE Projects(
	Id INT UNSIGNED NOT NULL AUTO_INCREMENT,
	NameProject VARCHAR(20) NOT NULL,
	NameClient VARCHAR(20) NOT NULL,
	StartDate CHAR(10) NOT NULL,
	EndDate CHAR(10) NOT NULL,
	PercentProjectCompletion FLOAT DEFAULT 1,
	NeedForProgrammers SMALLINT UNSIGNED DEFAULT 0,
	PRIMARY KEY (Id)
) ENGINE=INNODB DEFAULT CHARACTER SET utf8;

CREATE TABLE Requirements(
	Id INT UNSIGNED NOT NULL AUTO_INCREMENT,
	ProjectId INT UNSIGNED NOT NULL,
	Description TEXT NOT NULL,
	TimeImplementation INT UNSIGNED NOT NULL,
	MarkOfImplementation BOOL DEFAULT FALSE,
	Priority TINYINT UNSIGNED NOT NULL,
	ProbabilityOfChange TINYINT UNSIGNED NOT NULL,
	FOREIGN KEY (ProjectId) REFERENCES Projects (Id) ON DELETE CASCADE,
	PRIMARY KEY (Id)
) ENGINE=INNODB DEFAULT CHARACTER SET utf8;

INSERT INTO Users(Login, Password, Role)
VALUES
("root", "4813494d137e1631bba301d5acab6e7bb7aa74ce1185d456565ef51d737677b2", 1);